FROM centos
RUN yum install -y java
VOLUME /tmp
EXPOSE 8080
ADD /target/HelloWorldMicroservice-1.0.0.jar dockerdemo.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/dockerdemo.jar"]
